const db = require('../../config/db');
const { resolveSchema } = require('../../utils/tenantResolver');
const { resolveEmployeeId } = require('../../services/hr/employeeResolver');
const { hasTransaction } = require('../../services/hr/hrPermissions');
const balanceEngine = require('../../services/hr/balanceEngine');
const error=(message,statusCode)=>Object.assign(new Error(message),{statusCode});
const permitted=(schema,req,code,action)=>req.user.is_super_admin||hasTransaction(schema,req.user.id,code,[action],req.user.is_super_admin);
async function listBalances(schema,client,employeeId,userId) { const employee=await client.query(`SELECT hire_date FROM ${schema}.employees WHERE id=$1`,[employeeId]); if(!employee.rows.length) throw error('Empleado no encontrado',404); const period=balanceEngine.resolvePeriod(employee.rows[0].hire_date); await client.query(`INSERT INTO ${schema}.hr_leave_balances (employee_id,balance_code,unit,base_entitlement,accrual_enabled) VALUES ($1,'vacation_days','days',0,FALSE),($1,'permission_hours','hours',0,FALSE) ON CONFLICT(employee_id,balance_code) DO NOTHING`,[employeeId]); const rows=await client.query(`SELECT * FROM ${schema}.hr_leave_balances WHERE employee_id=$1 ORDER BY balance_code FOR UPDATE`,[employeeId]); return Promise.all(rows.rows.map(async balance=>{await balanceEngine.ensureAccrual(client,schema,balance,period,userId); const value=await balanceEngine.getAvailableBalance(client,schema,balance.id,period); return {balance_code:balance.balance_code,unit:balance.unit,period_start:period.start,period_end:period.end,entitlement:Number(value.entitlement),accrued:Number(value.accrued),reserved:Number(value.reserved),consumed:Number(value.consumed),available:Number(value.available)};})); }
async function respondBalances(req,res,employeeId) { const client=await db.getClient(); try { const {schema}=await resolveSchema(req); await client.query('BEGIN'); const balances=await listBalances(schema,client,employeeId,req.user.id); await client.query('COMMIT'); res.json(balances); } catch(cause) { await client.query('ROLLBACK').catch(()=>undefined); res.status(cause.statusCode||500).json({error:cause.message||'No fue posible obtener los saldos'}); } finally { client.release(); } }
exports.getMine=async(req,res)=>{try{const {schema}=await resolveSchema(req);if(!await permitted(schema,req,'hr_my_profile','can_view'))throw error('No tenés permiso para ver tus saldos',403);const id=await resolveEmployeeId(schema,req.user.id);if(!id)throw error('No tenés un perfil de empleado vinculado',403);return respondBalances(req,res,id);}catch(cause){res.status(cause.statusCode||500).json({error:cause.message});}};
exports.getByEmployee=async(req,res)=>{try{const {schema}=await resolveSchema(req);if(!await permitted(schema,req,'hr_employees','can_view'))throw error('No tenés permiso para ver saldos de empleados',403);return respondBalances(req,res,Number(req.params.employeeId));}catch(cause){res.status(cause.statusCode||500).json({error:cause.message});}};
exports.updateBalance=async(req,res)=>{if(req.user.read_only)return res.status(403).json({error:'Operación no permitida en modo solo lectura'});const client=await db.getClient();try{const {schema}=await resolveSchema(req);if(!await permitted(schema,req,'hr_employees','can_edit'))throw error('No tenés permiso para configurar saldos',403);const {base_entitlement,accrual_enabled,accrual_per_month,accrual_cap,unit}=req.body;const q=await client.query(`INSERT INTO ${schema}.hr_leave_balances (employee_id,balance_code,base_entitlement,accrual_enabled,accrual_per_month,accrual_cap,unit,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(employee_id,balance_code) DO UPDATE SET base_entitlement=EXCLUDED.base_entitlement,accrual_enabled=EXCLUDED.accrual_enabled,accrual_per_month=EXCLUDED.accrual_per_month,accrual_cap=EXCLUDED.accrual_cap,unit=EXCLUDED.unit,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP RETURNING *`,[Number(req.params.employeeId),req.params.balanceCode,base_entitlement,accrual_enabled,accrual_per_month,accrual_cap,unit,req.user.id]);res.json(q.rows[0]);}catch(cause){res.status(cause.statusCode||500).json({error:cause.message||'No fue posible actualizar el saldo'});}finally{client.release();}};
exports.createAdjustment=async(req,res)=>{if(req.user.read_only)return res.status(403).json({error:'Operación no permitida en modo solo lectura'});const client=await db.getClient();try{const {schema}=await resolveSchema(req);if(!await permitted(schema,req,'hr_employees','can_admin'))throw error('No tenés permiso para administrar saldos',403);const quantity=Number(req.body.quantity);if(!Number.isFinite(quantity)||quantity===0)throw error('quantity debe ser un número distinto de cero',400);await client.query('BEGIN');const row=await client.query(`SELECT b.*,e.hire_date FROM ${schema}.hr_leave_balances b JOIN ${schema}.employees e ON e.id=b.employee_id WHERE b.employee_id=$1 AND b.balance_code=$2 FOR UPDATE`,[req.params.employeeId,req.params.balanceCode]);if(!row.rows.length)throw error('Saldo no encontrado',404);const period=balanceEngine.resolvePeriod(row.rows[0].hire_date);const movement=await client.query(`INSERT INTO ${schema}.hr_balance_movements (leave_balance_id,employee_id,balance_code,movement_type,signed_quantity,period_start,period_end,notes,created_by) VALUES ($1,$2,$3,'hr_adjustment',$4,$5,$6,$7,$8) RETURNING *`,[row.rows[0].id,row.rows[0].employee_id,row.rows[0].balance_code,quantity,period.start,period.end,req.body.notes||null,req.user.id]);await client.query('COMMIT');res.status(201).json(movement.rows[0]);}catch(cause){await client.query('ROLLBACK').catch(()=>undefined);res.status(cause.statusCode||500).json({error:cause.message||'No fue posible registrar el ajuste'});}finally{client.release();}};
exports.listMovements=async(req,res)=>{try{const {schema}=await resolveSchema(req);if(!await permitted(schema,req,'hr_employees','can_view'))throw error('No tenés permiso para ver movimientos',403);const mode=req.query.period||'current';if(!['current','all'].includes(mode))throw error('period debe ser current o all',400);let period=[];if(mode==='current'){const employee=await db.query(`SELECT hire_date FROM ${schema}.employees WHERE id=$1`,[req.params.employeeId]);if(!employee.rows.length)throw error('Empleado no encontrado',404);const value=balanceEngine.resolvePeriod(employee.rows[0].hire_date);period=[value.start,value.end];}const q=await db.query(`SELECT m.* FROM ${schema}.hr_balance_movements m WHERE m.employee_id=$1 AND m.balance_code=$2 ${period.length?'AND m.period_start=$3 AND m.period_end=$4':''} ORDER BY m.movement_type,m.created_at DESC,m.id DESC`,[req.params.employeeId,req.params.balanceCode,...period]);res.json(q.rows);}catch(cause){res.status(cause.statusCode||500).json({error:cause.message||'No fue posible obtener los movimientos'});}};
