<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { CheckCircle2, Plus, Search } from 'lucide-vue-next';
import NxrSlidePanel from '../../components/NxrSlidePanel.vue';
import { usePermissions } from '../../composables/usePermissions';
import { treasuryCounterpartiesService } from '../../services/treasuryCounterpartiesService';
import { treasuryCashSessionsService } from '../../services/treasuryCashSessionsService';
import { treasuryDocumentsService } from '../../services/treasuryDocumentsService';
import { useTreasuryReceiptsStore } from '../../stores/treasuryReceipts';
import { useTreasuryDisbursementsStore } from '../../stores/treasuryDisbursements';
import type { TreasuryCounterparty, TreasuryCashSession } from '../../types/treasury';
import type { TreasuryDocument } from '../../types/treasuryDocuments';

const props = defineProps<{ kind: 'receipt' | 'disbursement' }>();
const { canDo, isReadOnly } = usePermissions();
const receipts = useTreasuryReceiptsStore();
const disbursements = useTreasuryDisbursementsStore();
const store: any = props.kind === 'receipt' ? receipts : disbursements;
const title = props.kind === 'receipt' ? 'Recibos' : 'Pagos Emitidos';
const documentDirection = props.kind === 'receipt' ? 'receivable' : 'payable';
const transaction = props.kind === 'receipt' ? 'treasury_receipts' : 'treasury_disbursements';
const numberField = props.kind === 'receipt' ? 'receipt_number' : 'disbursement_number';
const dateField = props.kind === 'receipt' ? 'receipt_date' : 'payment_date';
const itemNumber = (item: any) => props.kind === 'receipt' ? item.receipt_number : item.disbursement_number;
const itemDate = (item: any) => props.kind === 'receipt' ? item.receipt_date : item.payment_date;
const panel = ref<'create' | 'apply' | null>(null);
const error = ref(''); const query = ref(''); const counterparties = ref<TreasuryCounterparty[]>([]); const sessions = ref<TreasuryCashSession[]>([]);
const selected = ref<any>(null); const openDocuments = ref<TreasuryDocument[]>([]); const detailDocuments = ref<Record<number, TreasuryDocument>>({});
const amounts = ref<Record<string, number>>({});
const form = ref<any>({ counterparty_id: 0, total_amount: 0, cash_session_id: null, payment_method: '', receipt_number: '', disbursement_number: '', receipt_date: '', payment_date: '' });
const canEdit = computed(() => !isReadOnly.value && (canDo(transaction, 'can_create') || canDo(transaction, 'can_edit')));
const filtered = computed(() => { const value = query.value.trim().toLowerCase(); return !value ? store.items : store.items.filter((item: any) => `${itemNumber(item)} ${item.counterparty_name || ''}`.toLowerCase().includes(value)); });
const appliedTotal = computed(() => Object.values(amounts.value).reduce((sum, value) => sum + (Number(value) || 0), 0));
const remaining = computed(() => Math.max(0, Number(selected.value?.total_amount || 0) - Number(selected.value?.applied_amount || 0)));
function money(value: number | null | undefined) { return new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(Number(value || 0)); }
function date(value: string) { return value ? new Date(value).toLocaleDateString('es-CL') : '—'; }
function key(documentId: number, installmentId?: number) { return `${documentId}-${installmentId || 'document'}`; }
function installmentRows(document: TreasuryDocument) { const installments = detailDocuments.value[document.id]?.installments || []; return installments.filter(item => Number(item.balance_amount) > 0); }
function isFullyApplied(item: any) { return Number(item.applied_amount || 0) >= Number(item.total_amount || 0) - 0.0001; }
function rowBalance(document: TreasuryDocument, installment?: any) { return Number(installment?.balance_amount ?? document.balance_amount); }
async function load() { await Promise.all([store.load(), treasuryCounterpartiesService.list({ status: 'active' }).then(r => counterparties.value = r.data), treasuryCashSessionsService.list({ status: 'open' }).then(r => sessions.value = r.data)]); }
onMounted(load);
function openCreate() { error.value = ''; const today = new Date().toISOString().slice(0, 10); form.value = { counterparty_id: counterparties.value[0]?.id || 0, total_amount: 0, cash_session_id: null, payment_method: '', receipt_number: '', disbursement_number: '', receipt_date: today, payment_date: today }; panel.value = 'create'; }
async function saveCreate() { const total = Number(form.value.total_amount); if (!form.value.counterparty_id) return error.value = 'Seleccioná una contraparte'; if (!form.value[numberField]?.trim()) return error.value = 'Ingresá el número del comprobante'; if (!Number.isFinite(total) || total <= 0) return error.value = 'El monto debe ser mayor que cero'; try { await store.create({ ...form.value, total_amount: total, cash_session_id: form.value.cash_session_id || null }); panel.value = null; } catch (cause: any) { error.value = cause?.response?.data?.error || 'No fue posible crear el comprobante'; } }
async function openApply(item: any) { error.value = ''; selected.value = item; amounts.value = {}; panel.value = 'apply'; try { const docs = (await treasuryDocumentsService.list(documentDirection, { counterparty_id: item.counterparty_id })).data.filter((doc: TreasuryDocument) => Number(doc.balance_amount) > 0 && doc.status !== 'void'); openDocuments.value = docs; const details = await Promise.all(docs.map(doc => treasuryDocumentsService.getById(documentDirection, doc.id))); detailDocuments.value = Object.fromEntries(details.map(result => [result.data.id, result.data])); } catch (cause: any) { error.value = cause?.response?.data?.error || 'No fue posible cargar los documentos abiertos'; } }
function applications() { const result: any[] = []; for (const document of openDocuments.value) { const installments = installmentRows(document); if (installments.length) { for (const installment of installments) { const amount = Number(amounts.value[key(document.id, installment.id)] || 0); if (amount > 0) result.push({ treasury_document_id: document.id, installment_id: installment.id, applied_amount: amount }); } } else { const amount = Number(amounts.value[key(document.id)] || 0); if (amount > 0) result.push({ treasury_document_id: document.id, applied_amount: amount }); } } return result; }
async function saveApply() { const values = applications(); if (!values.length) return error.value = 'Ingresá al menos un monto para aplicar'; if (appliedTotal.value > remaining.value + 0.0001) return error.value = 'La suma aplicada no puede superar el saldo disponible del comprobante'; for (const application of values) { const doc = openDocuments.value.find(item => item.id === application.treasury_document_id)!; const installment = application.installment_id ? installmentRows(doc).find(item => item.id === application.installment_id) : undefined; if (application.applied_amount > rowBalance(doc, installment) + 0.0001) return error.value = installment ? 'El monto aplicado supera el saldo pendiente de una cuota' : 'El monto aplicado supera el saldo pendiente de un documento'; } try { await store.apply(selected.value.id, values); panel.value = null; } catch (cause: any) { error.value = cause?.response?.data?.error || 'No fue posible aplicar el comprobante'; } }
</script>

<template>
  <div class="flex flex-col gap-5 p-3 sm:p-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-xl font-semibold nxr-text">{{ title }}</h1><p class="text-xs nxr-text-muted">Registro y aplicación de comprobantes.</p></div><button v-if="canEdit" class="nxr-btn nxr-btn-primary" @click="openCreate"><Plus :size="15" /> Nuevo {{ kind === 'receipt' ? 'recibo' : 'pago' }}</button></div>
    <div class="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3"><Search :size="16" class="nxr-text-muted" /><input v-model="query" class="w-full bg-transparent py-2 text-sm nxr-text outline-none" placeholder="Buscar por número o contraparte" /></div>
    <p v-if="store.error" class="text-sm text-red-400">{{ store.error }}</p><p v-if="store.loading" class="py-10 text-center text-sm nxr-text-muted">Cargando comprobantes...</p>
    <div v-else><p v-if="!filtered.length" class="py-12 text-center text-sm nxr-text-muted">No hay comprobantes para mostrar.</p><div class="hidden overflow-x-auto md:block"><table class="w-full text-left text-sm"><thead class="text-xs uppercase nxr-text-muted"><tr><th class="p-3">Número</th><th class="p-3">Contraparte</th><th class="p-3">Fecha</th><th class="p-3 text-right">Total</th><th class="p-3 text-right">Aplicado</th><th class="p-3"></th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id" class="border-t border-white/10"><td class="p-3 nxr-text">{{ itemNumber(item) }}</td><td class="p-3 nxr-text-muted">{{ item.counterparty_name }}</td><td class="p-3 nxr-text-muted">{{ date(itemDate(item)) }}</td><td class="p-3 text-right nxr-text">{{ money(item.total_amount) }}</td><td class="p-3 text-right nxr-text-muted">{{ money(item.applied_amount) }}</td><td class="p-3 text-right"><button v-if="canEdit && item.status === 'active' && !isFullyApplied(item)" class="nxr-btn nxr-btn-secondary" @click="openApply(item)">Aplicar</button></td></tr></tbody></table></div><div class="grid grid-cols-1 gap-3 md:hidden"><article v-for="item in filtered" :key="item.id" class="rounded-xl border border-white/10 p-4"><div class="flex justify-between gap-3"><strong class="nxr-text">{{ itemNumber(item) }}</strong><span class="text-xs nxr-text-muted">{{ date(itemDate(item)) }}</span></div><p class="mt-2 text-sm nxr-text-muted">{{ item.counterparty_name }}</p><div class="mt-3 flex justify-between text-sm"><span class="nxr-text-muted">Total</span><strong class="nxr-text">{{ money(item.total_amount) }}</strong></div><div class="mt-1 flex justify-between text-sm"><span class="nxr-text-muted">Aplicado</span><span class="nxr-text-muted">{{ money(item.applied_amount) }}</span></div><button v-if="canEdit && item.status === 'active' && !isFullyApplied(item)" class="nxr-btn nxr-btn-secondary mt-4 w-full" @click="openApply(item)">Aplicar</button></article></div></div>
    <NxrSlidePanel :open="panel === 'create'" :title="kind === 'receipt' ? 'Nuevo recibo' : 'Nuevo pago emitido'" size="md" @close="panel = null"
    draft-key="views/treasury/TreasuryPaymentApplicationsScreen.vue#1"
    :draft-entity="kind"
    :draft-state="{ form }"><div class="space-y-3"><label class="block text-xs nxr-text-muted">Número<input v-model="form[numberField]" class="mt-1 w-full rounded-xl border border-white/10 bg-white/5 p-2 nxr-text" /></label><label class="block text-xs nxr-text-muted">Contraparte<select v-model.number="form.counterparty_id" class="mt-1 w-full rounded-xl border border-white/10 bg-white/5 p-2 nxr-text"><option :value="0">Seleccioná una contraparte</option><option v-for="item in counterparties" :key="item.id" :value="item.id">{{ item.name_snapshot }}</option></select></label><label class="block text-xs nxr-text-muted">Fecha<input v-model="form[dateField]" type="date" class="mt-1 w-full rounded-xl border border-white/10 bg-white/5 p-2 nxr-text" /></label><label class="block text-xs nxr-text-muted">Monto<input v-model.number="form.total_amount" type="number" min="0.01" step="0.01" class="mt-1 w-full rounded-xl border border-white/10 bg-white/5 p-2 nxr-text" /></label><label class="block text-xs nxr-text-muted">Método de pago<input v-model="form.payment_method" class="mt-1 w-full rounded-xl border border-white/10 bg-white/5 p-2 nxr-text" /></label><label class="block text-xs nxr-text-muted">Sesión de caja opcional<select v-model="form.cash_session_id" class="mt-1 w-full rounded-xl border border-white/10 bg-white/5 p-2 nxr-text"><option :value="null">Sin sesión de caja</option><option v-for="item in sessions" :key="item.id" :value="item.id">{{ item.cash_register_name || 'Caja #' + item.cash_register_id }}</option></select></label><p v-if="error" class="text-sm text-red-400">{{ error }}</p></div><template #footer><button class="nxr-btn nxr-btn-primary" :disabled="store.saving" @click="saveCreate">Guardar</button></template></NxrSlidePanel>
    <NxrSlidePanel :open="panel === 'apply'" title="Aplicar comprobante" size="lg" @close="panel = null"
    draft-key="views/treasury/TreasuryPaymentApplicationsScreen.vue#2"
    :draft-entity="selected?.id ?? `${kind}:apply`"
    :draft-state="{ amounts }"><div class="space-y-4"><div class="rounded-xl border border-white/10 bg-white/5 p-3 text-sm"><p class="nxr-text">{{ itemNumber(selected || {}) }} · {{ selected?.counterparty_name }}</p><p class="mt-1 nxr-text-muted">Disponible: <strong class="nxr-text">{{ money(remaining) }}</strong> · A aplicar: <strong class="nxr-text">{{ money(appliedTotal) }}</strong></p></div><p class="text-xs nxr-text-muted">Distribuí el monto entre uno o varios documentos o cuotas. La aplicación se envía completa en una sola operación.</p><p v-if="!openDocuments.length && !error" class="py-8 text-center text-sm nxr-text-muted">No hay documentos abiertos para esta contraparte.</p><section v-for="document in openDocuments" :key="document.id" class="rounded-xl border border-white/10 p-3"><div class="flex justify-between gap-3"><div><p class="text-sm font-medium nxr-text">{{ document.internal_number }}</p><p class="text-xs nxr-text-muted">Saldo: {{ money(document.balance_amount) }}</p></div></div><div v-if="installmentRows(document).length" class="mt-3 space-y-2"><div v-for="installment in installmentRows(document)" :key="installment.id" class="grid grid-cols-1 gap-2 rounded-lg bg-white/5 p-2 sm:grid-cols-[1fr_9rem]"><span class="text-sm nxr-text-muted">Cuota {{ installment.installment_number }} · saldo {{ money(installment.balance_amount) }}</span><input v-model.number="amounts[key(document.id, installment.id)]" type="number" min="0" :max="installment.balance_amount" step="0.01" class="rounded-lg border border-white/10 bg-black/20 p-2 nxr-text" placeholder="Monto" /></div></div><div v-else class="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-[1fr_9rem]"><span class="text-sm nxr-text-muted">Aplicar al documento</span><input v-model.number="amounts[key(document.id)]" type="number" min="0" :max="document.balance_amount" step="0.01" class="rounded-lg border border-white/10 bg-black/20 p-2 nxr-text" placeholder="Monto" /></div></section><p v-if="error" class="text-sm text-red-400">{{ error }}</p></div><template #footer><button class="nxr-btn nxr-btn-primary" :disabled="store.saving || !openDocuments.length" @click="saveApply"><CheckCircle2 :size="15" /> Confirmar aplicación</button></template></NxrSlidePanel>
  </div>
</template>
