<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ArrowLeft, Plus, Save, Search } from 'lucide-vue-next';
import { useTreasuryDocumentsStore } from '../../stores/treasuryDocuments';
import { useTreasurySettingsStore } from '../../stores/treasurySettings';
import type { TreasuryDirection, TreasuryDocumentPayload } from '../../types/treasuryDocuments';
const props=defineProps<{direction:TreasuryDirection; title:string; basePath:string}>(); const route=useRoute(); const router=useRouter(); const store=useTreasuryDocumentsStore(); const settings=useTreasurySettingsStore(); const q=ref(''); const saving=ref(false); const error=ref(''); const id=computed(()=>Number(route.params.id||0)); const detail=computed(()=>route.name===props.basePath+'-new'||!!id.value); const form=ref<TreasuryDocumentPayload>({document_type:props.direction==='receivable'?'sale_invoice':'purchase_invoice',counterparty_id:0,issue_date:new Date().toISOString().slice(0,10),currency:'CLP',total_amount:0,subtotal:0,tax_total:0,discount_total:0,notes:''});
function money(value:number){return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(value||0));}
async function boot(){await settings.counterparties.load({status:'active'});if(detail.value&&id.value){const doc=await store.loadOne(props.direction,id.value);form.value={document_type:doc.document_type,counterparty_id:doc.counterparty_id,issue_date:doc.issue_date.slice(0,10),due_date:doc.due_date?.slice(0,10)||null,external_number:doc.external_number||'',currency:doc.currency,total_amount:Number(doc.total_amount),subtotal:Number(doc.total_amount),tax_total:0,discount_total:0,notes:doc.notes||''};}else if(!detail.value)await store.load(props.direction,{q:q.value||undefined});}
onMounted(boot);watch(()=>route.fullPath,boot);watch(q,()=>{if(!detail.value)store.load(props.direction,{q:q.value||undefined});});
async function save(){if(!form.value.counterparty_id||!form.value.issue_date||Number(form.value.total_amount)<=0){error.value='Contraparte, fecha y total mayor que cero son requeridos';return;}saving.value=true;try{const doc=await store.create(props.direction,{...form.value,counterparty_id:Number(form.value.counterparty_id),total_amount:Number(form.value.total_amount),subtotal:Number(form.value.total_amount)});router.push(props.basePath+'/'+doc.id);}catch(e:any){error.value=e?.response?.data?.error||'No fue posible guardar el documento';}finally{saving.value=false;}}
</script>
<template><div class="flex min-h-[calc(100vh-5rem)] flex-col gap-5 p-3 sm:p-6"><template v-if="!detail"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-xl font-semibold text-white">{{ title }}</h1><p class="text-xs text-white/40">Documentos financieros pendientes de gestión.</p></div><button class="nxr-btn nxr-btn-primary" @click="router.push(basePath+'/new')"><Plus :size="15" /> Nuevo documento</button></div><div class="relative"><Search :size="14" class="absolute left-3 top-3 text-white/30"/><input v-model="q" placeholder="Buscar..." class="w-full rounded-xl border border-white/10 bg-white/5 py-2 pl-9 text-sm text-white"/></div><p v-if="store.error" class="text-red-400">{{ store.error }}</p><div class="grid grid-cols-1 gap-3 md:grid-cols-2"><button v-for="doc in store.items" :key="doc.id" class="rounded-xl border border-white/10 p-4 text-left" @click="router.push(basePath+'/'+doc.id)"><p class="font-semibold text-white">{{ doc.internal_number }}</p><p class="text-xs text-white/40">{{ doc.counterparty_name }} · {{ doc.issue_date }}</p><p class="mt-2 text-sm text-white">{{ money(doc.balance_amount) }} pendiente</p></button></div></template><template v-else><div class="flex items-center justify-between"><button class="text-white/60" @click="router.push(basePath)"><ArrowLeft :size="20"/></button><button class="nxr-btn nxr-btn-primary" :disabled="saving" @click="save"><Save :size="15"/> Guardar</button></div><div class="grid grid-cols-1 gap-3 rounded-xl border border-white/10 p-4 md:grid-cols-3"><select v-model.number="form.counterparty_id" class="rounded-xl border border-white/10 bg-white/5 p-2 text-white"><option :value="0">Seleccionar contraparte</option><option v-for="item in settings.counterparties.items" :key="item.id" :value="item.id">{{ item.name_snapshot }}</option></select><input v-model="form.issue_date" type="date" class="rounded-xl border border-white/10 bg-white/5 p-2 text-white"/><input v-model="form.due_date" type="date" class="rounded-xl border border-white/10 bg-white/5 p-2 text-white"/><input v-model="form.external_number" placeholder="Folio externo" class="rounded-xl border border-white/10 bg-white/5 p-2 text-white"/><select v-model="form.document_type" class="rounded-xl border border-white/10 bg-white/5 p-2 text-white"><option value="sale_invoice">Factura</option><option value="sale_note">Nota</option><option value="debit_note">Nota de débito</option><option value="credit_note">Nota de crédito</option></select><input v-model.number="form.total_amount" type="number" min="1" placeholder="Total" class="rounded-xl border border-white/10 bg-white/5 p-2 text-white"/><textarea v-model="form.notes" placeholder="Notas" class="md:col-span-3 rounded-xl border border-white/10 bg-white/5 p-2 text-white"/></div><p v-if="error" class="text-sm text-red-400">{{ error }}</p></template></div></template>
