<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { CirclePlus, XCircle } from 'lucide-vue-next';
import NxrSlidePanel from '../../components/NxrSlidePanel.vue';
import { usePermissions } from '../../composables/usePermissions';
import { useHrRequestsStore } from '../../stores/hrRequests';
import type { HrRequestPayload } from '../../types/hr';

const store = useHrRequestsStore();
const { canDo, isReadOnly } = usePermissions();
const panelOpen = ref(false); const saving = ref(false); const formError = ref('');
const form = ref<HrRequestPayload>({ request_type_id: null, title: '', description: '', start_date: '', end_date: '' });
const canCreate = computed(() => !isReadOnly.value && canDo('hr_requests', 'can_create'));
const statusLabel = (status: string) => ({ submitted: 'Enviada', supervisor_approved: 'Aprobada por supervisor', supervisor_rejected: 'Rechazada por supervisor', hr_approved: 'Aprobada', hr_rejected: 'Rechazada por RRHH', annulled: 'Anulada' }[status] || status);
function resetForm() { form.value = { request_type_id: null, title: '', description: '', start_date: '', end_date: '' }; formError.value = ''; }
function openCreate() { resetForm(); panelOpen.value = true; }
async function save() { if (!form.value.request_type_id) { formError.value = 'El tipo de solicitud es requerido'; return; } saving.value = true; formError.value = ''; try { await store.create(form.value); panelOpen.value = false; } catch (cause: any) { formError.value = cause?.response?.data?.error || 'No fue posible enviar la solicitud'; } finally { saving.value = false; } }
async function annul(id: number) { if (isReadOnly.value) return; try { await store.act(id, 'annul'); } catch (cause: any) { formError.value = cause?.response?.data?.error || 'No fue posible anular la solicitud'; } }
onMounted(() => Promise.all([store.loadMine(), store.loadTypes()]));
</script>
<template><div class="flex flex-col gap-5 p-3 sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-xl font-semibold nxr-text">Mis solicitudes</h1><p class="text-xs nxr-text-muted">Consultá y enviá tus solicitudes de Recursos Humanos.</p></div><button v-if="canCreate" class="nxr-btn nxr-btn-primary justify-center" @click="openCreate"><CirclePlus :size="16" /> Nueva solicitud</button></div><p v-if="formError" class="text-sm text-red-400">{{ formError }}</p><div v-if="store.loading" class="space-y-2"><div v-for="index in 5" :key="index" class="h-20 animate-pulse rounded-xl bg-white/5" /></div><p v-else-if="store.error" class="py-12 text-center text-sm text-red-400">{{ store.error }}</p><p v-else-if="!store.mine.length" class="py-16 text-center text-sm nxr-text-soft">Todavía no tenés solicitudes.</p><div v-else class="grid grid-cols-1 gap-3 lg:grid-cols-2"><article v-for="request in store.mine" :key="request.id" class="rounded-xl border border-white/10 p-4" :style="{ background: 'var(--nexora-glass-bg)' }"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-semibold nxr-text">{{ request.title || request.request_type_name || 'Solicitud de RRHH' }}</p><p class="mt-1 text-xs nxr-text-muted">{{ request.request_type_name || `Tipo #${request.request_type_id}` }} · {{ new Date(request.created_at).toLocaleDateString() }}</p></div><span class="rounded-full bg-white/10 px-2 py-1 text-xs nxr-text-muted">{{ statusLabel(request.status) }}</span></div><p v-if="request.description" class="mt-3 line-clamp-2 text-sm nxr-text-muted">{{ request.description }}</p><div class="mt-4 flex justify-end"><button v-if="['submitted', 'supervisor_approved'].includes(request.status) && !isReadOnly" class="inline-flex items-center gap-1 text-xs text-red-300 hover:text-red-200" @click="annul(request.id)"><XCircle :size="14" /> Anular</button></div></article></div><NxrSlidePanel :open="panelOpen" title="Nueva solicitud" size="sm" @close="panelOpen = false"
    draft-key="views/hr/screens_hr_requests.vue#1"
    :draft-entity="'create'"
    :draft-state="{ form }"><div class="space-y-4"><div><label class="mb-1 block text-xs nxr-text-muted">Tipo de solicitud *</label><select v-model.number="form.request_type_id" class="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm nxr-text outline-none"><option :value="null" disabled>Seleccioná un tipo</option><option v-for="type in store.types" :key="type.id" :value="type.id">{{ type.name }}</option></select></div><div><label class="mb-1 block text-xs nxr-text-muted">Título</label><input v-model="form.title" class="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm nxr-text outline-none" /></div><div class="grid gap-3 sm:grid-cols-2"><div><label class="mb-1 block text-xs nxr-text-muted">Desde</label><input v-model="form.start_date" type="date" class="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm nxr-text" /></div><div><label class="mb-1 block text-xs nxr-text-muted">Hasta</label><input v-model="form.end_date" type="date" class="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm nxr-text" /></div></div><div><label class="mb-1 block text-xs nxr-text-muted">Descripción</label><textarea v-model="form.description" rows="4" class="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm nxr-text outline-none" /></div><p v-if="formError" class="text-xs text-red-400">{{ formError }}</p></div><template #footer><button class="nxr-btn nxr-btn-primary" :disabled="saving" @click="save">{{ saving ? 'Enviando...' : 'Enviar' }}</button></template></NxrSlidePanel></div></template>
