<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { Check, X } from 'lucide-vue-next';
import NxrSlidePanel from '../../components/NxrSlidePanel.vue';
import { usePermissions } from '../../composables/usePermissions';
import { useHrRequestsStore } from '../../stores/hrRequests';
import type { HrRequest } from '../../types/hr';
const store = useHrRequestsStore(); const { canDo, isReadOnly } = usePermissions(); const panelOpen = ref(false); const selectedRequestId = ref<number | null>(null); const actionError = ref(''); const actionLoading = ref(false); const comment = ref('');
const statusLabel = (status: string) => ({ submitted: 'Pendiente de supervisor', supervisor_approved: 'Pendiente de RRHH' }[status] || status);
async function open(request: HrRequest) { actionError.value = ''; comment.value = ''; selectedRequestId.value = request.id; panelOpen.value = true; try { await store.loadOne(request.id); } catch (cause: any) { actionError.value = cause?.response?.data?.error || 'No fue posible cargar la solicitud'; } }
async function decide(action: 'approve' | 'reject') { if (!store.current || isReadOnly.value) return; actionLoading.value = true; actionError.value = ''; try { await store.act(store.current.id, action, comment.value || undefined); panelOpen.value = false; } catch (cause: any) { actionError.value = cause?.response?.data?.error || 'No fue posible registrar la decisión'; } finally { actionLoading.value = false; } }
onMounted(store.loadApprovals);
</script>
<template><div class="flex flex-col gap-5 p-3 sm:p-6"><div><h1 class="text-xl font-semibold text-white">Aprobaciones</h1><p class="text-xs text-white/40">Solicitudes pendientes de tu revisión.</p></div><div v-if="store.loading" class="space-y-2"><div v-for="index in 5" :key="index" class="h-20 animate-pulse rounded-xl bg-white/5" /></div><p v-else-if="store.error" class="py-12 text-center text-sm text-red-400">{{ store.error }}</p><p v-else-if="!store.approvals.length" class="py-16 text-center text-sm text-white/35">No hay solicitudes pendientes.</p><div v-else class="grid grid-cols-1 gap-3 lg:grid-cols-2"><button v-for="request in store.approvals" :key="request.id" class="rounded-xl border border-white/10 p-4 text-left transition hover:border-white/25" :style="{ background: 'var(--nexora-glass-bg)' }" @click="open(request)"><div class="flex justify-between gap-3"><div class="min-w-0"><p class="truncate text-sm font-semibold text-white">{{ request.title || request.request_type_name || 'Solicitud de RRHH' }}</p><p class="mt-1 text-xs text-white/45">{{ request.employee_name || 'Empleado' }} · {{ request.request_type_name }}</p></div><span class="shrink-0 rounded-full bg-amber-400/10 px-2 py-1 text-xs text-amber-200">{{ statusLabel(request.status) }}</span></div></button></div><NxrSlidePanel :open="panelOpen" title="Revisar solicitud" size="md" @close="panelOpen = false"
    draft-key="views/hr/screens_hr_request_approvals.vue#1"
    :draft-entity="selectedRequestId"
    :draft-state="{ comment }"
    :draft-setters="{ comment: (value) => comment = value }"><div v-if="store.detailLoading" class="space-y-3"><div v-for="index in 4" :key="index" class="h-12 animate-pulse rounded bg-white/5" /></div><div v-else-if="store.current" class="space-y-5"><section><p class="text-xs text-white/45">{{ store.current.employee_name }} · {{ store.current.request_type_name }}</p><h3 class="mt-1 text-base font-semibold text-white">{{ store.current.title || 'Solicitud de RRHH' }}</h3><p class="mt-3 whitespace-pre-line text-sm text-white/70">{{ store.current.description || 'Sin descripción.' }}</p><p v-if="store.current.start_date || store.current.end_date" class="mt-3 text-xs text-white/45">{{ store.current.start_date || 'Sin inicio' }} — {{ store.current.end_date || 'Sin fin' }}</p></section><section><h4 class="text-sm font-medium text-white">Historial</h4><ol class="mt-3 space-y-3 border-l border-white/15 pl-4"><li v-for="item in store.current.history" :key="item.id" class="text-sm text-white/65"><p>{{ statusLabel(item.to_status) }}</p><p v-if="item.note" class="mt-1 text-xs text-white/40">{{ item.note }}</p><p class="mt-1 text-xs text-white/35">{{ new Date(item.created_at).toLocaleString() }}</p></li></ol></section><div v-if="!isReadOnly && (canDo('hr_request_approvals', 'can_approve') || canDo('hr_request_approvals', 'can_edit'))"><label class="mb-1 block text-xs text-white/50">Comentario</label><textarea v-model="comment" rows="3" class="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-white outline-none" /></div><p v-if="actionError" class="text-xs text-red-400">{{ actionError }}</p></div><template #footer><template v-if="store.current && !isReadOnly && (canDo('hr_request_approvals', 'can_approve') || canDo('hr_request_approvals', 'can_edit'))"><button class="nxr-btn bg-red-500/80 text-white hover:bg-red-500" :disabled="actionLoading" @click="decide('reject')"><X :size="15" /> Rechazar</button><button class="nxr-btn nxr-btn-primary" :disabled="actionLoading" @click="decide('approve')"><Check :size="15" /> Aprobar</button></template></template></NxrSlidePanel></div></template>
